# Generated by Django 4.0 on 2024-10-06 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterUniqueTogether(
            name='tank',
            unique_together={('name', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'location')},
        ),
    ]
