# Generated by Django 4.0 on 2024-03-04 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_sensor_tank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='tank',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='data.tank'),
        ),
    ]
