# Generated by Django 4.0 on 2024-08-08 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_sensor_tank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='tank',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='data.tank'),
        ),
        migrations.AlterField(
            model_name='tank',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tank',
            name='type',
            field=models.CharField(choices=[('Storage', 'Storage'), ('Well', 'Well'), ('Reservoir', 'Reservoir'), ('Tank', 'Tank'), ('Other', 'Other')], default='Storage', max_length=255),
        ),
    ]
