# Generated by Django 4.0 on 2024-08-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_group_location_alter_group_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['sensor_id'], 'verbose_name': 'Sensor', 'verbose_name_plural': 'Sensors'},
        ),
        migrations.AlterModelOptions(
            name='tank',
            options={'ordering': ['name'], 'verbose_name': 'Tank', 'verbose_name_plural': 'Tanks'},
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='tank',
            unique_together={('name', 'group')},
        ),
    ]
