[supervisord]
nodaemon=true

[program:gunicorn]
command=/usr/local/bin/gunicorn backend.wsgi:application --bind 0.0.0.0:8000
directory=/code
user=root
autostart=true
autorestart=true

[program:daphne]
command=/usr/local/bin/daphne backend.asgi:application --bind 0.0.0.0:8001
directory=/code
user=root
autostart=true
autorestart=true
