# Generated by Django 4.1.7 on 2023-07-20 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TankGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("location", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Tank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Storage", "Storage"),
                            ("Well", "Well"),
                            ("Reservoir", "Reservoir"),
                            ("Tank", "Tank"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("capacity", models.PositiveIntegerField()),
                ("is_active", models.BooleanField()),
                ("dimensions", models.CharField(max_length=100)),
                ("material", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=100)),
                (
                    "tankGroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tanks",
                        to="tanks.tankgroup",
                    ),
                ),
            ],
        ),
    ]
