# Generated by Django 4.1.7 on 2023-03-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WaterTank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userId", models.IntegerField()),
                ("location", models.TextField()),
                ("name", models.TextField()),
                ("capacity", models.IntegerField()),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                ("z", models.IntegerField()),
                ("material", models.TextField()),
                ("brandName", models.TextField()),
            ],
        ),
    ]
