# Generated by Django 4.1.7 on 2023-07-19 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tanks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="tankgroup", name="isActive",),
    ]
