# Generated by Django 4.1.7 on 2023-07-21 17:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tanks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tank",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="tank",
            name="date_modified",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="tankgroup",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 21, 17, 11, 15, 458940, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="tankgroup",
            name="date_modified",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 21, 17, 11, 15, 458940, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="tankgroup",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tankgroup",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tank",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="tank", name="name", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="tankgroup",
            name="location",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="tankgroup",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
