# Generated by Django 4.2.2 on 2023-07-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tanks", "0002_tank_date_created_tank_date_modified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tank",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="tank",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="tankgroup",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="tankgroup",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
