# Generated by Django 4.1.7 on 2023-04-06 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_tank_tankgroup_delete_watertank"),
    ]

    operations = [
        migrations.RemoveField(model_name="tankgroup", name="tank",),
        migrations.AddField(
            model_name="tank",
            name="TankGroup",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.tankgroup",
            ),
        ),
    ]
