# Generated by Django 4.0 on 2023-07-25 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0003_alter_tank_date_created_alter_tank_date_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tank',
            name='is_active',
        ),
    ]
