# Generated by Django 4.0 on 2023-07-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0004_remove_tank_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
