# Generated by Django 4.0 on 2023-09-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useraccount_groups_and_more'),
        ('tanks', '0005_tank_isactive'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TankGroup',
            new_name='Group',
        ),
        migrations.RenameField(
            model_name='tank',
            old_name='tankGroup',
            new_name='group',
        ),
    ]
