# Generated by Django 4.0 on 2024-10-13 21:10

from django.db import migrations, models
import django.db.models.deletion
import timescale.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0003_remove_sensor_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=20)),
                ('rate', models.FloatField()),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Chunk',
                'verbose_name_plural': 'Chunks',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('value', models.FloatField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='timeseries.channel')),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='timeseries.chunk')),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('Temperature', 'Temperature'), ('Pressure', 'Pressure'), ('Level', 'Level'), ('Counter', 'Counter'), ('Vibration', 'Vibration'), ('Speed', 'Speed'), ('Other', 'Other')], default='Level', max_length=100)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='resources.sensor')),
            ],
            options={
                'verbose_name': 'Measure',
                'verbose_name_plural': 'Measures',
                'unique_together': {('label', 'sensor')},
            },
        ),
        migrations.AddField(
            model_name='chunk',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='timeseries.measure'),
        ),
        migrations.AddField(
            model_name='channel',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='timeseries.measure'),
        ),
    ]
