# Generated by Django 5.1.2 on 2024-11-03 20:53

import django.utils.timezone
import timescale.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeseries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='time',
            field=timescale.db.models.fields.TimescaleDateTimeField(default=django.utils.timezone.now, interval='1 hour'),
        ),
    ]
