# Generated by Django 5.1.2 on 2025-02-09 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeseries', '0002_alter_record_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='rate',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
