# Generated by Django 4.2.2 on 2023-07-21 21:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tanks", "0003_alter_tank_date_created_alter_tank_date_modified_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200)),
                ("serial_number", models.CharField(max_length=50, unique=True)),
                ("manufacturer", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("installation_date", models.DateField()),
                ("calibration_date", models.DateField()),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "elevation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("maintenance_interval", models.DurationField(blank=True, null=True)),
                (
                    "tank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tanks.tank"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("water_level", models.FloatField()),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("battery_voltage", models.FloatField(blank=True, null=True)),
                ("signal_strength", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("is_alert", models.BooleanField(default=False)),
                ("alert_message", models.TextField(blank=True, null=True)),
                ("pressure", models.FloatField(blank=True, null=True)),
                ("wind_speed", models.FloatField(blank=True, null=True)),
                ("wind_direction", models.FloatField(blank=True, null=True)),
                ("rain_rate", models.FloatField(blank=True, null=True)),
                ("soil_moisture", models.FloatField(blank=True, null=True)),
                ("air_quality", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_data",
                        to="sensors.sensor",
                    ),
                ),
            ],
        ),
    ]
