# Generated by Django 4.0 on 2024-06-16 17:05

from django.db import migrations
import django.utils.timezone
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorlog',
            name='time',
            field=timescale.db.models.fields.TimescaleDateTimeField(default=django.utils.timezone.now, interval='1 day'),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='time',
            field=timescale.db.models.fields.TimescaleDateTimeField(default=django.utils.timezone.now, interval='1 day'),
        ),
    ]
