# Generated by Django 4.0 on 2024-02-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorlog',
            name='sensor_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='sensor_id',
            field=models.IntegerField(default=-1),
        ),
    ]
