# Generated by Django 4.0 on 2023-07-26 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0005_tank_isactive'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='tank',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tanks.tank'),
        ),
    ]
