# Generated by Django 4.0 on 2023-10-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='last_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
