# Generated by Django 4.0 on 2023-08-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_alter_sensor_tank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='elevation',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='location',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='name',
        ),
    ]
