# Generated by Django 4.0 on 2024-08-09 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_group_location_alter_group_name_and_more'),
        ('sensors', '0002_alter_sensorlog_time_alter_sensorreading_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorlog',
            options={'ordering': ['-time'], 'verbose_name': 'Sensor Log', 'verbose_name_plural': 'Sensor Logs'},
        ),
        migrations.AlterModelOptions(
            name='sensorreading',
            options={'ordering': ['-time'], 'verbose_name': 'Sensor Reading', 'verbose_name_plural': 'Sensor Readings'},
        ),
        migrations.AlterField(
            model_name='sensorlog',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='data.sensor'),
        ),
        migrations.AlterField(
            model_name='sensorlog',
            name='status',
            field=models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=25),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='data.sensor'),
        ),
    ]
