# Generated by Django 4.0 on 2023-08-06 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0005_tank_isactive'),
        ('sensors', '0003_remove_sensor_elevation_remove_sensor_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TankSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_sensor', to='sensors.sensor')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_sensor', to='tanks.tank')),
            ],
        ),
    ]
