# Generated by Django 4.0 on 2023-08-06 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_tanksensor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='tank',
        ),
    ]
