#ifndef CONSTANTS_H
#define CONSTANTS_H

//////////////////
/// APP STATUS ///
//////////////////

#define DEBUG True

enum STATUS_CODE {
    WIFI_CONNECTED_,
    WIFI_DISCONNECTED_,

    MQTT_CONNECTED_,
    MQTT_DISCONNECTED_,
    MQTT_SUBSCRIBED_,
    MQTT_UNSUBSCRIBED_,

    SENSOR_CONNECTED_,
    SENSOR_DISCONNECTED_,
};

enum LOG_CODE {
    WIFI_CONNECTION,
    WIFI_DISCONNECTION,
    WIFI_CONNECTION_ATTEMPT,
    WIFI_CONNECTION_SUCCESS,
    WIFI_CONNECTION_FAILED,
    WIFI_CONNECTION_TIMEOUT,
    WIFI_CONNECTION_RETRY,
    WIFI_CONNECTION_RETRY_ATTEMPT,
    WIFI_CONNECTION_RETRY_SUCCESS,
    WIFI_CONNECTION_RETRY_FAILED,
    WIFI_CONNECTION_RETRY_TIMEOUT,

    MQTT_CONNECTION,
    MQTT_DISCONNECTION,
    MQTT_SUBSCRIBED,
    MQTT_UNSUBSCRIBED,
    MQTT_PUBLISHED,
    MQTT_SUBSCRIPTION_FAILED,
    MQTT_PUBLISH_FAILED,
    MQTT_MESSAGE_RECEIVED,
    MQTT_MESSAGE_PROCESSED,
    MQTT_MESSAGE_PROCESSING_FAILED,
    MQTT_MESSAGE_PROCESSING_SUCCESS,

    SENSOR_CONNECTED,
    SENSOR_DISCONNECTED,
    SENSOR_DATA_RECEIVED,
    SENSOR_DATA_PROCESSING_SUCCESS,
    SENSOR_DATA_PROCESSING_FAILED,
    SENSOR_DATA_PROCESSING_TIMEOUT,
    SENSOR_DATA_PROCESSING_RETRY,
};

///////////////////
/// APP CONFIG ////
///////////////////

#define APP_NAME "Sensor"
#define APP_VERSION "0.1"

#define EEPROM_SIZE 512

/// MANAGERS ///

//  WIFI
#define SERVER_PORT 80
#define WIFI_CONNECTION_TIMEOUT 250
#define SSID_START_ADDR 0
#define PASSWORD_START_ADDR 100

// MQTT
#define MQTT_BROKER "192.168.1.13"
#define MQTT_PORT 1883

// HARDWARE
#define TRIGGER_PIN D3  // RX
#define ECHO_PIN D4     // TX
#define MAX_DISTANCE 100

// WEBSERVER
#define WEB_SERVER_PORT 80
#define WEBSOCKET_PORT 80

// PUMP
#define RELE_PIN D8
#define START_PIN D1
#define START_LED_PIN D0
#define STOP_PIN D2
#define STOP_LED_PIN D5

#endif  // CONSTANTS_H
