#ifndef CONSTANTS_H
#define CONSTANTS_H

//////////////////
/// APP STATUS ///
//////////////////

#define DEBUG True

enum STATUS_CODE {
    WIFI_CONNECTED_,
    WIFI_DISCONNECTED_,

    MQTT_CONNECTED_,
    MQTT_DISCONNECTED_,
    MQTT_SUBSCRIBED_,
    MQTT_UNSUBSCRIBED_,

    SENSOR_CONNECTED_,
    SENSOR_DISCONNECTED_,
};

enum LOG_CODE {
    WIFI_CONNECTION,
    WIFI_DISCONNECTION,
    WIFI_CONNECTION_ATTEMPT,
    WIFI_CONNECTION_SUCCESS,
    WIFI_CONNECTION_FAILED,
    WIFI_CONNECTION_TIMEOUT,
    WIFI_CONNECTION_RETRY,
    WIFI_CONNECTION_RETRY_ATTEMPT,
    WIFI_CONNECTION_RETRY_SUCCESS,
    WIFI_CONNECTION_RETRY_FAILED,
    WIFI_CONNECTION_RETRY_TIMEOUT,

    MQTT_CONNECTION,
    MQTT_DISCONNECTION,
    MQTT_SUBSCRIBED,
    MQTT_UNSUBSCRIBED,
    MQTT_PUBLISHED,
    MQTT_SUBSCRIPTION_FAILED,
    MQTT_PUBLISH_FAILED,
    MQTT_MESSAGE_RECEIVED,
    MQTT_MESSAGE_PROCESSED,
    MQTT_MESSAGE_PROCESSING_FAILED,
    MQTT_MESSAGE_PROCESSING_SUCCESS,

    SENSOR_CONNECTED,
    SENSOR_DISCONNECTED,
    SENSOR_DATA_RECEIVED,
    SENSOR_DATA_PROCESSING_SUCCESS,
    SENSOR_DATA_PROCESSING_FAILED,
    SENSOR_DATA_PROCESSING_TIMEOUT,
    SENSOR_DATA_PROCESSING_RETRY,
};

///////////////////
/// APP CONFIG ////
///////////////////

#define APP_NAME "Sensor"
#define APP_VERSION "0.1"
#define APP_AUTHOR "Tesfaye Carreras"

#define EEPROM_SIZE 512

/// CONNECTIONS ///

//  WIFI
#define WIFI_SSID "ONO1D77"
#define WIFI_PASSWORD "dVy68naGZU5d"
#define PUBLIC_IP "2.152.26.61"

// MQTT
#define MQTT_BROKER "192.168.1.13"
#define MQTT_PORT 1883

// HARDWARE
#define TRIGGER_PIN RX  // RX -> D5
#define ECHO_PIN TX     // TX -> D6
#define MAX_DISTANCE 450

// WEBSERVER
#define WEB_SERVER_PORT 80

// PUMP
#define RELE_PIN D8
#define START_PIN D1
#define START_LED_PIN D0
#define STOP_PIN D2
#define STOP_LED_PIN D5

#endif  // CONSTANTS_H
