#ifndef UTILS_H
#define UTILS_H

#include "../App/AppConfig.h"
#include "constants.h"
#include "types.h"

/* 
  This function is used to generate a unique ID for each sensor.
  The ID is generated by combining the board ID and the flash chip ID.
  The ID is then hashed using the MD5 algorithm.
  The resulting hash is returned as a string.
  Parameters:
    - boardId: String representing the board ID.
    - flashChipId: String representing the flash chip ID.
  Returns:
    - String: The unique ID generated for the sensor.
*/
String generateId(String boardId, String flashChipId) {
  MD5Builder md5;
  md5.begin();
  md5.add(boardId);
  md5.add(flashChipId);
  md5.calculate();
  return md5.toString();
}

/* 
  This function is used to blink the built-in LED.
  The LED turns on for 100 milliseconds, then turns off for 100 milliseconds.
*/
void blink() {
  digitalWrite(LED_BUILTIN, HIGH);
  delay(100);
  digitalWrite(LED_BUILTIN, LOW);
  delay(100);
}

/* 
  This function returns the string representation of the corresponding message key.
  Parameters:
    - key: Enum representing the message key.
  Returns:
    - const char*: The string representation of the message key.
*/
const char* ETS(MESSAGE_PARAMETER key) {
  switch (key) {
    // Metadata
    case MESSAGE_ID:
      return "101";
    case TIMESTAMP:
      return "102";
    case SENSOR_ID:
      return "103";
    case SENSOR_TIME:
      return "104";
    case MESSAGE_TYPE:
      return "105";
    case VERSION:
      return "106";

    // Action
    case ACTION_TYPE:
      return "201";
    case ACTION_NAME:
      return "202";
    default:
      return "9999";
  }
  // Handle the case when the enum value doesn't match any case.
  return "-";
}

#endif  // UTILS_H
