# Generated by Django 4.0 on 2024-10-12 09:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_edited_at'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['device_id'], 'verbose_name': 'Sensor', 'verbose_name_plural': 'Sensors'},
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='sensor_id',
            new_name='device_id',
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'user')},
        ),
        migrations.RemoveField(
            model_name='tank',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='date_modified',
        ),
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, verbose_name='edition date'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, verbose_name='edition date'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='installation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='name',
            field=models.CharField(default='default_sensor_name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='status',
            field=models.CharField(choices=[('Idle', 'Idle'), ('Connecting', 'Connecting'), ('Connected', 'Connected'), ('Disconnecting', 'Disconnecting'), ('Disconnected', 'Disconnected'), ('Error', 'Error')], default='Idle', max_length=50),
        ),
        migrations.AddField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('Temperature', 'Temperature'), ('Pressure', 'Pressure'), ('Level', 'Level'), ('Counter', 'Counter'), ('Vibration', 'Vibration'), ('Speed', 'Speed'), ('Other', 'Other')], default='Level', max_length=100),
        ),
        migrations.AddField(
            model_name='tank',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tank',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='edited_at',
            field=models.DateTimeField(auto_now=True, verbose_name='edition date'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='tank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='resources.tank'),
        ),
        migrations.AlterUniqueTogether(
            name='sensor',
            unique_together={('name', 'tank')},
        ),
        migrations.RemoveField(
            model_name='group',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='group',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='date_modified',
        ),
    ]
