# Generated by Django 4.0 on 2024-10-13 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_sensor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='type',
        ),
    ]
