# Generated by Django 4.0 on 2024-10-08 22:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
                ('lon', models.FloatField(help_text='Longitude of the city.')),
                ('lat', models.FloatField(help_text='Latitude of the city.')),
                ('date', models.DateField(help_text='Date of the weather data.')),
                ('weather_main', models.CharField(help_text='Main weather condition.', max_length=255)),
                ('weather_description', models.CharField(help_text='Description of the weather condition.', max_length=255)),
                ('temperature', models.FloatField(help_text='Temperature in Celsius for the day.')),
                ('feels_like', models.FloatField(help_text='Feels like temperature in Celsius for the day.')),
                ('temp_min', models.FloatField(help_text='Minimum temperature for the day.')),
                ('temp_max', models.FloatField(help_text='Maximum temperature for the day.')),
                ('pressure', models.IntegerField(help_text='Atmospheric pressure in hPa for the day.')),
                ('humidity', models.IntegerField(help_text='Humidity percentage for the day.')),
                ('wind_speed', models.FloatField(help_text='Average wind speed in meters per second for the day.')),
                ('wind_deg', models.IntegerField(help_text='Average wind direction in degrees for the day.')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of the daily weather data entry.')),
            ],
            options={
                'verbose_name': 'Daily Weather Data',
                'verbose_name_plural': 'Daily Weather Data',
                'unique_together': {('city_name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Current',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
                ('lon', models.FloatField(help_text='Longitude of the city.')),
                ('lat', models.FloatField(help_text='Latitude of the city.')),
                ('weather_main', models.CharField(help_text='Main weather condition.', max_length=255)),
                ('weather_description', models.CharField(help_text='Description of the weather condition.', max_length=255)),
                ('temperature', models.FloatField(help_text='Current temperature in Celsius.')),
                ('feels_like', models.FloatField(help_text='Feels like temperature in Celsius.')),
                ('temp_min', models.FloatField(help_text='Minimum temperature in the current weather data.')),
                ('temp_max', models.FloatField(help_text='Maximum temperature in the current weather data.')),
                ('pressure', models.IntegerField(help_text='Atmospheric pressure in hPa.')),
                ('humidity', models.IntegerField(help_text='Humidity percentage.')),
                ('wind_speed', models.FloatField(help_text='Wind speed in meters per second.')),
                ('wind_deg', models.IntegerField(help_text='Wind direction in degrees.')),
                ('timestamp', models.DateTimeField(auto_now=True, help_text='Timestamp of the weather data update.')),
            ],
            options={
                'verbose_name': 'Current Weather Data',
                'verbose_name_plural': 'Current Weather Data',
                'unique_together': {('city_name',)},
            },
        ),
    ]
