# Generated by Django 5.1.2 on 2025-02-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='current',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='current',
            name='city_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
