# Generated by Django 4.0 on 2024-08-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_dailyweatherdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyweatherdata',
            name='city_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dailyweatherdata',
            name='weather_main',
            field=models.CharField(max_length=255),
        ),
    ]
