# Generated by Django 4.0 on 2024-08-09 00:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_dailyweatherdata_city_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyweatherdata',
            options={'verbose_name': 'Daily Weather Data', 'verbose_name_plural': 'Daily Weather Data'},
        ),
        migrations.AlterField(
            model_name='currentweatherdata',
            name='feels_like',
            field=models.FloatField(help_text='Feels like temperature in Celsius.'),
        ),
        migrations.AlterField(
            model_name='currentweatherdata',
            name='humidity',
            field=models.IntegerField(help_text='Humidity percentage.'),
        ),
        migrations.AlterField(
            model_name='currentweatherdata',
            name='lat',
            field=models.FloatField(help_text='Latitude of the city.'),
        ),
        migrations.AlterField(
            model_name='currentweatherdata',
            name='lon',
            field=models.FloatField(help_text='Longitude of the city.'),
        ),
        migrations.AlterField(
            model_name='currentweatherdata',
            name='pressure',
            field=models.IntegerField(help_text='Atmospheric pressure in hPa.'),
        ),
        migrations.AlterField(
            model_name='currentweatherdata',
            name='temp_max',
            field=models.FloatField(help_text='Maximum temperature in the current weather data.'),
        ),
        migrations.AlterField(
            model_name='currentweatherdata',
            name='temp_min',
            field=models.FloatField(help_text='Minimum temperature in the current weather data.'),
        ),
        migrations.AlterField(
            model_name='currentweatherdata',
            name='temperature',
            field=models.FloatField(help_text='Current temperature in Celsius.'),
        ),
        migrations.AlterField(
            model_name='currentweatherdata',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of the weather data update.'),
        ),
        migrations.AlterField(
            model_name='currentweatherdata',
            name='weather_description',
            field=models.CharField(help_text='Description of the weather condition.', max_length=255),
        ),
        migrations.AlterField(
            model_name='currentweatherdata',
            name='weather_main',
            field=models.CharField(help_text='Main weather condition.', max_length=255),
        ),
        migrations.AlterField(
            model_name='currentweatherdata',
            name='wind_deg',
            field=models.IntegerField(help_text='Wind direction in degrees.'),
        ),
        migrations.AlterField(
            model_name='currentweatherdata',
            name='wind_speed',
            field=models.FloatField(help_text='Wind speed in meters per second.'),
        ),
        migrations.AlterField(
            model_name='dailyweatherdata',
            name='date',
            field=models.DateField(help_text='Date of the weather data.'),
        ),
        migrations.AlterField(
            model_name='dailyweatherdata',
            name='feels_like',
            field=models.FloatField(help_text='Feels like temperature in Celsius for the day.'),
        ),
        migrations.AlterField(
            model_name='dailyweatherdata',
            name='humidity',
            field=models.IntegerField(help_text='Humidity percentage for the day.'),
        ),
        migrations.AlterField(
            model_name='dailyweatherdata',
            name='lat',
            field=models.FloatField(help_text='Latitude of the city.'),
        ),
        migrations.AlterField(
            model_name='dailyweatherdata',
            name='lon',
            field=models.FloatField(help_text='Longitude of the city.'),
        ),
        migrations.AlterField(
            model_name='dailyweatherdata',
            name='pressure',
            field=models.IntegerField(help_text='Atmospheric pressure in hPa for the day.'),
        ),
        migrations.AlterField(
            model_name='dailyweatherdata',
            name='temp_max',
            field=models.FloatField(help_text='Maximum temperature for the day.'),
        ),
        migrations.AlterField(
            model_name='dailyweatherdata',
            name='temp_min',
            field=models.FloatField(help_text='Minimum temperature for the day.'),
        ),
        migrations.AlterField(
            model_name='dailyweatherdata',
            name='temperature',
            field=models.FloatField(help_text='Temperature in Celsius for the day.'),
        ),
        migrations.AlterField(
            model_name='dailyweatherdata',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of the daily weather data entry.'),
        ),
        migrations.AlterField(
            model_name='dailyweatherdata',
            name='weather_description',
            field=models.CharField(help_text='Description of the weather condition.', max_length=255),
        ),
        migrations.AlterField(
            model_name='dailyweatherdata',
            name='weather_main',
            field=models.CharField(help_text='Main weather condition.', max_length=255),
        ),
        migrations.AlterField(
            model_name='dailyweatherdata',
            name='wind_deg',
            field=models.IntegerField(help_text='Average wind direction in degrees for the day.'),
        ),
        migrations.AlterField(
            model_name='dailyweatherdata',
            name='wind_speed',
            field=models.FloatField(help_text='Average wind speed in meters per second for the day.'),
        ),
    ]
