# Generated by Django 4.0 on 2024-08-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_alter_dailyweatherdata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentweatherdata',
            options={'verbose_name': 'Current Weather Data', 'verbose_name_plural': 'Current Weather Data'},
        ),
        migrations.AlterUniqueTogether(
            name='currentweatherdata',
            unique_together={('city_name',)},
        ),
    ]
