# Generated by Django 4.0 on 2024-10-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
